### PR TITLE
configs/turris1x/kernel: Allow RTC NVMEM access

### PR DESCRIPTION
**Pull request by oskar456**
In Linux 4.13, a new kernel option was introduced to allow userspace
access to RTC NVMEM. This option is off by default, making the NVMEM
inaccessable. Since there is at least one application utilizing it, this
patch adds `/sys/class/rtc/rtc0/device/nvram` back.

Please note that this has been untested as I was not able to get get the build machine running. But it is just a kernel option, what could possibly go wrong? ;)

### CODE REVIEW

**Comment by Cynerd** [comment]
@oskar456 what is that application you are talking about? Just for curiosity I have not looked enough in to it.

And yes what could possibly go wrong. I have nothing against this with exception of: does it makes sense to enable this in all boards not just for Turris 1.x?

**Comment by oskar456** [comment]
> @oskar456 what is that application you are talking about? Just for curiosity I have not looked enough in to it.

The [TurrisClock](https://github.com/oskar456/turrisclock/blob/master/nvramstore.py) of course! :smile: 

> 
> And yes what could possibly go wrong. I have nothing against this with exception of: does it makes sense to enable this in all boards not just for Turris 1.x?

If there's any NVMEM in the SoCes used by other boards, then sure, why not. I just checked the driver for `rtc-armada38x` used in Omnia and it seems there's no such RAM. Nevertheless, enabling those options globally should not cause any harm, only make the kernel a little bit bigger.

**Comment by BKPepe** [comment]
Ok, guys. Thank you for contributing! We appreciate it. I'm merging this PR as it is.
I'm going to cherry-pick to branches v5.0 (HBD), v4.1 (HBL), v4.0 (HBK). It should be included as part of Turris OS 4.0.2.

**Review by Cynerd — APPROVED** [review]

**Comment by BKPepe** [comment]
For reference:
**HBK** - branch `v4.0`: https://github.com/CZ-NIC/turris-build/commit/e09c946dec355de98d0ffe4431aec4334cd38977
**HBL** - branch `v4.1`: https://github.com/CZ-NIC/turris-build/commit/66645fe5dcc33258f73afa8c4764780fb701954d
**HBD** - branch `v5.0`: https://github.com/CZ-NIC/turris-build/commit/39f9ab5f4bf0aa8225d6704036c75d523276be6f

**Pull request merged**
