### PR TITLE
Disable OpenWRT procfs patch

### PR DESCRIPTION
**Pull request by SuperQ**
Add patch to allow downstream projects to configure the kernel
CONFIG_PROC_STRIPPED patch.

Re-enable some `/proc` files disabled by default in OpenWRT[0]. This
enables several usefule proc files like `/proc/net/netstat` and
`/proc/net/snmp`.

[0]: https://git.openwrt.org/?p=openwrt/openwrt.git;a=blob;f=target/linux/generic/hack-4.14/902-debloat_proc.patch;h=c5f6397be1443db0130210b6685eccc77200a296;hb=refs/tags/v19.07.2

Signed-off-by: Ben Kochie <superq@gmail.com>

### CODE REVIEW

**Review by Cynerd — APPROVED** [review]
LGTM

I have nothing against that. It makes sense for our beefy routers.

**Comment by Cynerd** [comment]
I approve this but I won't merge this because I am sure that this won't work. I am unable to found such symbol in OpenWrt configuration.

It is provided directly in `target/linux/generic/config-4.14`.

It is required to add that symbol in upstream so it is correctly propagated to kernel configuration. See file `config/Config-kernel.in`.

**Comment by SuperQ** [comment]
@Cynerd Thanks, that's too bad it's hard coded like that. I can attempt to do the upstream patch.

Is there another workaround method for Turris to apply build-time patches to the upstream code? Otherwise it'll be probably years to get this patch done, upstreamed, and merged into turris. :frowning: 

The funny part is, the patch disables the `/proc/net/snmp`, file but not `/proc/net/snmp6`. But whatever it's doing is breaking IPv6 metrics. I haven't looked too closely at the way the kernel patch works.

**Comment by Cynerd** [comment]
> Is there another workaround method for Turris to apply build-time patches to the upstream code? Otherwise it'll be probably years to get this patch done, upstreamed, and merged into turris. 

You can place that patch to directory `/patches/openwrt/to-upstream`. All of those pathes (`patches/$FEED/$TYPE/*.path`) are automatically applied by `compile_pkgs`. There are few that do the same thing for for example leds on Omnia.

> The funny part is, the patch disables the `/proc/net/snmp`, file but not `/proc/net/snmp6`. But whatever it's doing is breaking IPv6 metrics. I haven't looked too closely at the way the kernel patch works.

I did and I hate it. It just disables execution of some functions. It is fragile and stupid. I am skeptical if it even brings some footprint reduction but ok.

**Comment by SuperQ** [comment]
Yea, I also questioned exactly how much overhead the patch reduces. :confused: 

I've added https://github.com/CZ-NIC/turris-build/pull/5

**Comment by Cynerd** [comment]
> Yea, I also questioned exactly how much overhead the patch reduces.

General problem with patches over configuration is that they fail to apply too often. That is why we prefer most of the contributions to be upstreamable. Yes it takes initially long time but in long run it makes it maintainable for us.

**Comment by SuperQ** [comment]
I agree, getting changes upstream is much preferred. I've added a new version of the patch here that should make it easier to upstream.

It would be nice to figure it the upstream "debloat" patch does anything useful, and maybe just get OpenWRT to drop the patch completely. :grin:

**Comment by Cynerd** [comment]
> I agree, getting changes upstream is much preferred. I've added a new version of the patch here that should make it easier to upstream.

Thank you. I am going to test it.

Just one another thing. Please rebase it on top of `hbl` branch. Master branch is obsolete now and we instead develop on top of `hb*` branches. Explanation is in workflow branch. Github is mirror and master stayed as default here. I already notified my colleague about it.

> It would be nice to figure it the upstream "debloat" patch does anything useful, and maybe just get OpenWRT to drop the patch completely.

Yeh that would be nice but I am not sure if I have capacity to do so. Fell free to check if it lovers kernel memory footprint or something. I am just not sure.

**Comment by SuperQ** [comment]
Well, I screwed that up. *sigh*

**Comment by VojtechMyslivec** [comment]
moved to #6

**Pull request closed without merging**
